const fakeCategories = [
  {
    id: 1,
    nome: "Masculino",
  },
  {
    id: 2,
    nome: "Feminino",
  },
  {
    id: 3,
    nome: "Infantil",
  },
  {
    id: 4,
    nome: "Cosmetico",
  },
  {
    id: 5,
    nome: "Roupa",
  },
];

const fakeConsumer = [
  {
    id: 1,
    nome: "Yago Jordas",
    email: "yago.jordas@academico.ifpb.edu.br",
    senha: "12345y",
    genero: "Masculino",
    cep: "5814000",
  },
  {
    id: 2,
    nome: "Luciene Izidro",
    email: "lucieneizidro@gmail.com",
    senha: "12345l",
    genero: "Feminino",
    cep: "5814000",
  },
];

// adicionar desconto em cada um dos produtos
const fakeProducts = [
  {
    id: 0,
    nome: "Vestido Longo Floral Vestido Longo Floral Vestido Longo Floral Vestido Longo Floral Vestido Longo Floral",
    sobre: "Vestido longo com estampa floral, tecido leve e decote em V.",
    valor: "$89.90",
    tamanho: "P, M, G",
    url: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTQAsazTC1nWvs2V3FxBtfkxhaLOaiqjP6QedtdDN9znXnTndf5Y7xrXot30ORBXznsbUZwRaOxc1Ys9nzHMyF22eFWjL0lQCFqKZx307-GUMb7YvcNRPa7FxraZ_R5-XqEBVcZof_d&usqp=CAc",
    estoque: 10,
    desconto: "10%",
    genero: fakeCategories[1].nome,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 1,
    nome: "Vestido Longo Floral",
    sobre: "Vestido longo com estampa floral, tecido leve e decote em V.",
    valor: "$89.90",
    tamanho: "P, M, G",
    url: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTQAsazTC1nWvs2V3FxBtfkxhaLOaiqjP6QedtdDN9znXnTndf5Y7xrXot30ORBXznsbUZwRaOxc1Ys9nzHMyF22eFWjL0lQCFqKZx307-GUMb7YvcNRPa7FxraZ_R5-XqEBVcZof_d&usqp=CAc",
    estoque: 15,
    desconto: "10%",
    genero: fakeCategories[1].nome,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 2,
    nome: "Camisa Social Masculina Slim",
    sobre: "Camisa social com modelagem slim fit e tecido de algodão.",
    valor: "$69.90",
    tamanho: "M, G, GG",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpRBQLeZgeWIj8OcMwePf-KwC64IFBbxCfTB1UVUUrbnhme9WPn8wxdaQ&s=10",
    estoque: 30,
    desconto: "0%",
    genero: fakeCategories[0].nome,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 3,
    nome: "Base Líquida Matte",
    sobre: "Base de alta cobertura com acabamento matte e longa duração.",
    valor: "$49.90",
    tamanho: "30ml",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRObovksoGw75wMFsgUVbo_AhjZEckEY1Uiyw&s",
    estoque: 50,
    desconto: "5%",
    genero: null,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 4,
    nome: "Batom Vermelho Intenso",
    sobre: "Batom cremoso com alta pigmentação e hidratação.",
    valor: "$29.90",
    tamanho: "3.5g",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhIyaPjjP0JGRWk-SpyPiz0ARl86UHqo8iwg&s",
    estoque: 80,
    desconto: "15%",
    genero: null,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 5,
    nome: "Calça Jeans Skinny Feminina",
    sobre: "Calça jeans com elastano, modelagem skinny, lavagem clara.",
    valor: "$109.90",
    tamanho: "36, 38, 40, 42",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyck3VGxyuOP8VCyB8US19NESMbP9Uj3RVTA&s",
    estoque: 25,
    desconto: "0%",
    genero: fakeCategories[1].nome,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 6,
    nome: "Moletom Oversized Unissex",
    sobre: "Moletom com capuz, bolsos frontais e tecido macio.",
    valor: "$119.90",
    tamanho: "M, G, GG",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjs-t-PQjQtDds0K7LGVCZyOYxY65hbQqEzA&s",
    estoque: 20,
    desconto: "10%",
    genero: null,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 7,
    nome: "Paleta de Sombras Nude",
    sobre: "Paleta com 12 cores neutras, acabamento matte e cintilante.",
    valor: "$59.90",
    tamanho: "12 cores",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyTO-erIL1KmyzTr1JhuEZNB9LLwe-knLzklynVBXDfgDkV6nVWZlL1nqK&s=10",
    estoque: 40,
    desconto: "5%",
    genero: null,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 8,
    nome: "Jaqueta Corta Vento Masculina",
    sobre: "Jaqueta leve, resistente à água, ideal para o dia a dia.",
    valor: "$139.90",
    tamanho: "G, GG, XGG",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTZ82ZuiZ96wShGLBnTarjuPt4FP4OLL12rqyVnYMvDpDT8QZds0YCk08&s=10",
    estoque: 12,
    desconto: "20%",
    genero: fakeCategories[0].nome,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 9,
    nome: "Creme Hidratante Corporal",
    sobre: "Hidratante com manteiga de karité para todos os tipos de pele.",
    valor: "$34.90",
    tamanho: "200ml",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQLPUAMOV80C2wtifqzMPd2NaEE2OksIOseOSyz4oTEL63IV98PtX7XKY&s=10",
    estoque: 60,
    desconto: "10%",
    genero: null,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 10,
    nome: "Saia Plissada Midi",
    sobre: "Saia midi plissada com elástico na cintura, tecido leve.",
    valor: "$79.90",
    tamanho: "P, M, G",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeEBdjku9ooqjJfUj9XUd2OytvPpWiwO8WpgxQHS8m7cdbie1ieG6j9FdE&s=10",
    estoque: 18,
    desconto: "0%",
    genero: fakeCategories[1].nome,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 11,
    nome: "Perfume Feminino Floral",
    sobre: "Fragrância delicada com notas de jasmim e baunilha.",
    valor: "$99.90",
    tamanho: "100ml",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEo_LHFMiqQ-QhlFndJeF7mN4vwM1fPC3sRg&s",
    estoque: 22,
    desconto: "15%",
    genero: fakeCategories[1].nome,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 12,
    nome: "Blusa Canelada Manga Longa",
    sobre: "Blusa justa, tecido canelado e gola alta.",
    valor: "$59.90",
    tamanho: "P, M, G",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_0LDT8ZTDhE2hqQ6LQwiMKNSfYyeXqnPZJw&s",
    estoque: 35,
    desconto: "5%",
    genero: fakeCategories[0].nome,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 13,
    nome: "Máscara de Cílios Volume Extra",
    sobre: "Máscara para cílios com efeito de volume intenso.",
    valor: "$39.90",
    tamanho: "10ml",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR16ODYpI9g8Bj5M-m_Xu9nu4eC6vCNP9d65LzVt_BHBtkpS3jXBr_CpxzC&s=10",
    estoque: 45,
    desconto: "10%",
    genero: fakeCategories[1].nome,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 14,
    nome: "Short Jeans Destroyed",
    sobre: "Short com barra desfiada e detalhes destroyed.",
    valor: "$69.90",
    tamanho: "36, 38, 40, 42",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRf298Px5AePEgToZRg9I6DJweCfgro5kw4fFW5vwMydVx8XboL61uYvJo&s=10",
    estoque: 28,
    desconto: "0%",
    genero: fakeCategories[1].nome,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 15,
    nome: "Sérum Facial Vitamina C",
    sobre: "Sérum antioxidante com vitamina C para luminosidade da pele.",
    valor: "$59.90",
    tamanho: "30ml",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3UNNkudd35UdLIpfJGD9B4-1TA5uwIx73Bg&s",
    estoque: 40,
    desconto: "10%",
    genero: null,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 16,
    nome: "Macacão Pantacourt",
    sobre: "Macacão com modelagem pantacourt e alças ajustáveis.",
    valor: "$129.90",
    tamanho: "P, M, G",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNrECkrUxN9I2mLRdpFwtRku_EfIUjw1X0p0u9t3Z_dXKEj1KNEqRUlhQ&s=10",
    estoque: 16,
    desconto: "0%",
    genero: null,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 17,
    nome: "Blazer Alfaiataria Feminino",
    sobre: "Blazer com corte reto, tecido estruturado e forro interno.",
    valor: "$149.90",
    tamanho: "P, M, G",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-GA4lPFPfa4SkiG066ZvTvXx8p8ECQI5O9BlkAObG5P-5P4klNO16kgo&s=10",
    estoque: 10,
    desconto: "15%",
    genero: fakeCategories[1].nome,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 18,
    nome: "Óleo Corporal Hidratante",
    sobre: "Óleo com toque seco e fragrância suave, hidratação profunda.",
    valor: "$44.90",
    tamanho: "150ml",
    url: "https://acdn-us.mitiendanube.com/stores/001/973/993/products/editada-14-1024-x-1024-px1-aed5e9886d9bd975e116397684168495-1024-1024.jpg",
    estoque: 38,
    desconto: "5%",
    genero: null,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 19,
    nome: "Tênis Casual Branco",
    sobre: "Tênis básico branco, solado emborrachado e confortável.",
    valor: "$119.90",
    tamanho: "37, 38, 39, 40, 41, 42",
    url: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTlkf6llnAJ9ruQ5LGIsGvIhKD3UdHT1ebO9V1jwDuiY9pAiQkm1nl-P-gghdXTeRmEnPLhIQST-zf5HqYcfqISNuNHxbZsAV7L9ewHahsv9_-I4VEmBHhz&usqp=CAc",
    estoque: 20,
    desconto: "0%",
    genero: null,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 20,
    nome: "Corretivo Líquido Alta Cobertura",
    sobre: "Corretivo com acabamento natural e alta cobertura.",
    valor: "$32.90",
    tamanho: "15ml",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaOqzT3YNEqkPMBf3btehdfoq9YcDs_mySdiXjMQVKTAG7gYbyfQ9jwICfugZm5sqdA5c&usqp=CAU",
    estoque: 55,
    desconto: "10%",
    genero: null,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 21,
    nome: "Regata Básica Algodão",
    sobre: "Regata básica 100% algodão, ideal para o dia a dia.",
    valor: "$29.90",
    tamanho: "P, M, G, GG",
    url: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSmeoiC3Mgxs7-YqwGL-C22BM6Ds0Azj6W3_g37k6dVwEP6EeCGJxXdD7xU8UhzR8GziZymW9SvQTcFi1VnIYKcjzJRwj_ykyLj5_8Ej4XOs4Ve74hPSxlFmqn-iIIoTdgXsqQ0dyw&usqp=CAc",
    estoque: 60,
    desconto: "0%",
    genero: null,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 22,
    nome: "Kit Pincéis de Maquiagem",
    sobre: "Kit com 12 pincéis para rosto e olhos, cerdas macias.",
    valor: "$79.90",
    tamanho: "12 unidades",
    url: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR3DgCxx5JqAMLT6oarJtkRcl4XJN5Wj9KiIyyy1qi23yiS3DaBmTO56YSsXDapJCnBTVA-8JH0805Q7kWqRjySI7Lu_ZeQDTm3WUczFqqERH5pOO_W__-JPon0ba15Mbls4wRz4KQP3xQ&usqp=CAc",
    estoque: 35,
    desconto: "10%",
    genero: null,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 23,
    nome: "Jaqueta Jeans Oversized",
    sobre: "Jaqueta jeans com lavagem média e modelagem oversized.",
    valor: "$149.90",
    tamanho: "M, G, GG",
    url: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQO5vqAM5AK14ETgx6OyLJn2XtaN4VaOtfeNLwjNgPo2FU9oHPybp-MaiNQllV4Del-cjtD96710M18YJd6gd6YeCSyFA-3grys5tTVp8-Q2c9GrutFLddulcU&usqp=CAc",
    estoque: 12,
    desconto: "0%",
    genero: null,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 24,
    nome: "Máscara Facial Argila",
    sobre: "Máscara de argila purificante, ideal para peles oleosas.",
    valor: "$24.90",
    tamanho: "100g",
    url: "https://s3.amazonaws.com/img.iluria.com/product/80428C/13FF10A/450xN.jpg",
    estoque: 45,
    desconto: "5%",
    genero: null,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 25,
    nome: "Calça Moletom Jogger",
    sobre: "Calça jogger em moletom, com elástico e cordão na cintura.",
    valor: "$99.90",
    tamanho: "P, M, G",
    url: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT5bO965YBxgeyf6068IkQBrwVdw1eIoZ-dytRpl2gyp8T61HLOHfa2pjpVv8HtL9-kJ03A8XZ_0cc6Vh25uBa0nyFKV8A3qFi5cng5y7EBVpQ0yM0R_JzMe7XwTs6Pgznc_oNl-do&usqp=CAc",
    estoque: 22,
    desconto: "10%",
    genero: null,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 26,
    nome: "Primer Facial Hidratante",
    sobre: "Primer que minimiza poros e hidrata a pele antes da maquiagem.",
    valor: "$39.90",
    tamanho: "30ml",
    url: "https://cdn.awsli.com.br/2748/2748567/produto/273887172/28---hidratante-anticraquelamento-zd26pqkjdr.png",
    estoque: 33,
    desconto: "5%",
    genero: null,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 27,
    nome: "Blusa Cropped Manga Bufante",
    sobre: "Blusa cropped com mangas bufantes e decote quadrado.",
    valor: "$64.90",
    tamanho: "P, M, G",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7Vgx8MkP3jl8N3OALeVeq5qMVNtfQB_N9ktzBDFybJSQ_NElPu_nu4ssp&s=10",
    estoque: 17,
    desconto: "0%",
    genero: fakeCategories[1].nome,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 28,
    nome: "Iluminador Facial Compacto",
    sobre: "Iluminador com partículas de brilho para efeito glow natural.",
    valor: "$35.90",
    tamanho: "10g",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz5SzdAhIFkjKm-2X9EleD5vi_QWYKvSLiQw&s",
    estoque: 42,
    desconto: "10%",
    genero: null,
    categoria: fakeCategories[3].nome,
  },
  {
    id: 29,
    nome: "Body de Renda Feminino",
    sobre: "Body em renda, sem bojo, ideal para looks sofisticados.",
    valor: "$89.90",
    tamanho: "P, M, G",
    url: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTRD39y3MnwFkCwEdyNUl_M9xffPWWVShQM1LY3mf-YxoxOYz_XmO3Un-jtfDYrmbQh3RBRDGdT3GluEe_9S3P610taj3TooHZAXa8Q3-h2V_r7sWszsPLcbCJ-AVuXmKDBXftbWQ&usqp=CAc",
    estoque: 14,
    desconto: "0%",
    genero: fakeCategories[1].nome,
    categoria: fakeCategories[4].nome,
  },
  {
    id: 30,
    nome: "Fixador de Maquiagem Spray",
    sobre: "Spray fixador que prolonga a duração da maquiagem.",
    valor: "$49.90",
    tamanho: "120ml",
    url: "https://cdn.sistemawbuy.com.br/arquivos/cad5cc7133685cdd8d0d7880d11cba96/produtos/668dab35e7691/b554be9b70-668dab6f1be5d.jpg",
    estoque: 50,
    desconto: "10%",
    genero: null,
    categoria: fakeCategories[3].nome,
  },
];

const fakeSale = [];

const fakeShopCar = [
  {
    id: 1,
    id_products: [1, 2, 3],
  },
  {
    id: 2,
    id_products: [1, 5, 8],
  },
];

const fakeCategoriesProducts = [
  {
    id_categories: 1,
    id_product: 1,
  },
  {
    id_categories: 1,
    id_product: 2,
  },
  {
    id_categories: 2,
    id_product: 3,
  },
  {
    id_categories: 2,
    id_product: 4,
  },
  {
    id_categories: 3,
    id_product: 5,
  },
  {
    id_categories: 3,
    id_product: 6,
  },
  {
    id_categories: 4,
    id_product: 7,
  },
  {
    id_categories: 4,
    id_product: 8,
  },
  {
    id_categories: 4,
    id_product: 9,
  },
  {
    id_categories: 4,
    id_product: 10,
  },
];

const fakeBuy = [];

export {
  fakeCategories,
  fakeConsumer,
  fakeProducts,
  fakeSale,
  fakeShopCar,
  fakeCategoriesProducts,
  fakeBuy,
};
